name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c "curl -L -o login.py https://raw.githubusercontent.com/blind-intruder/test12/refs/heads/main/login.py"
          cmd /c "curl -L -o loop.bat https://raw.githubusercontent.com/blind-intruder/test12/refs/heads/main/loop.bat"
          cmd /c "curl -L -o show.bat https://raw.githubusercontent.com/blind-intruder/test12/refs/heads/main/show.bat"
          cmd /c 'certutil -urlcache -split -f "https://github.com/rustdesk/rustdesk/releases/download/1.2.1/rustdesk-1.2.1-x86_64.exe" rustdesk.exe'
          powershell -Command "Invoke-WebRequest 'https://github.com/chieunhatnang/VM-QuickConfig/releases/download/1.6.1/VMQuickConfig.exe' -OutFile 'C:\Users\Public\Desktop\VMQuickConfig.exe'"
          cmd /c "pip install pyautogui --quiet"
          cmd /c "pip install psutil --quiet"
          cmd /c "curl -s -L -o time.py https://raw.githubusercontent.com/blind-intruder/test12/refs/heads/main/time.py"
          powershell -Command "Set-LocalUser -Name 'runneradmin' -Password (ConvertTo-SecureString -AsPlainText 'Pakistan@9' -Force)"
          cmd /c 'start "" "rustdesk.exe"'
          cmd /c "python login.py"
